name: autofix linting errors
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  job01:
    if: contains(github.event.comment.body, 'autofixme!')
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '18.16.0'
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
