name: autofix linting errors
on:
  pull_request:
  push:
    branches: [develop]
jobs:
  job01:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
