name: autofix linting errors
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  job01:
    if: contains(github.event.comment.body, 'autofixme!')
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
